server:
  port: 8888
spring:
  profiles: dev
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
<<<<<<< HEAD
=======

>>>>>>> d3f36f14eeaa21c02bd50733f7012ffacc8b6b73
      routes:
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: auth_service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        - id: transporter_service
          uri: lb://transporter-service
          predicates:
            - Path=/transporter-service/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true



    


 
