spring:
  profiles: dev
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/transport
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
<<<<<<< HEAD
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my_group
=======
>>>>>>> d3f36f14eeaa21c02bd50733f7012ffacc8b6b73

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
