server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/lkjj-lkjj/Transport.git

#由于github网站不稳定，所以连接gitee网站，gitee网站的配置文件与github上的配置文件相同
          uri: https://gitee.com/shirleyviola/prediction.git
          force-pull: true
          username: 18800134465
          password: 1543186808wsx
