#server:
#  port: 8888
##  注意：gateway会不支持下划线的命名方式，所以routers中的uri以及predicates和application.name中应命名成中杆线的形式
#spring:
#  application:
#    name: gateway-service
#  main:
#    allow-bean-definition-overriding: true
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: '*'
#            allowedMethods: '*'
#            allowedHeaders: '*'
#      routes:
#        - id: user_service
#          uri: lb://user-service
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - StripPrefix=1
#
#        - id: auth_service
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth-service/**
#          filters:
#            - StripPrefix=1
#
#        - id: transporter_service
#          uri: lb://transporter-service
#          predicates:
#            - Path=/transporter-service/**
#          filters:
#            - StripPrefix=1
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost
#    prefer-ip-address: true

